repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: cargo-check
      - id: fmt
      - id: clippy
  - repo: local
    hooks:
      - id: cargo-readme
        name: cargo-readme
        entry: cargo readme > README.md
        language: script
        files: \.rs$
      