// src/macros/constrained_type.rs

// This is the internal "factory" for the newtype.
#[macro_export]
#[doc(hidden)]
macro_rules! __floco_internal_newtype_impl {
    (
        $(#[$outer:meta])*, $vis:vis, $TypeName:ident, $InnerType:ty,
        |$val_id:ident| $validator:expr, $error_msg:expr
    ) => {
        ::paste::paste! {
            #[doc = "A marker struct for the " $TypeName " constrained type."]
            #[derive(Debug, Copy, Clone, Default)]
            $vis struct [<$TypeName Constraint>];

            // --- The NEW, UNIFIED Constrained Impl ---
            // This applies the `const` keyword only when `runtime-defaults` is NOT active.
            impl #[cfg_attr(not(feature = "runtime-defaults"), const)]
            $crate::Constrained<$InnerType> for [<$TypeName Constraint>] {
                fn is_valid($val_id: $InnerType) -> bool { $validator }
                fn emit_error(value: $InnerType) -> Self::Error { $crate::ValidationError { value, message: $error_msg } }
            }

            // --- The Newtype Struct (remains the same) ---
            #[doc = "A validated newtype generated by the `constrained_type!` macro."]
            $(#[$outer])*
            #[derive(Debug, Copy, Clone, serde::Serialize, serde::Deserialize)]
            #[serde(transparent)]
            $vis struct $TypeName(pub $crate::Floco<$InnerType, [<$TypeName Constraint>]>);

            // ... (the rest of the macro remains the same) ...
            impl $TypeName {
                /// Creates a new, validated instance of this type.
                pub fn try_new(value: $InnerType) -> Result<Self, $crate::ValidationError<$InnerType>> {
                    Ok(Self($crate::Floco::<_, [<$TypeName Constraint>]>::try_new(value)?))
                }
                /// Returns the inner validated value.
                pub fn get(&self) -> $InnerType { (self.0).0 }
            }

            impl ::core::ops::Deref for $TypeName {
                type Target = $InnerType;
                fn deref(&self) -> &Self::Target { &(self.0).0 }
            }
        }
    };
}
