// src/macros/constrained_type.rs

#[macro_export]
#[doc(hidden)]
macro_rules! __floco_const_impl {
    ($($body:tt)*) => {
        impl const $($body)*
    };
}

#[macro_export]
#[doc(hidden)]
macro_rules! __floco_internal_newtype_impl {
    (
        $(#[$outer:meta])* ,
        $vis:vis,
        $TypeName:ident,
        $(< $($gen:tt)+ >)? ,
        $InnerType:ty,
        |$val_id:ident| $validator:expr,
        $error_msg:expr
    ) => {
        ::paste::paste! {
            #[doc = "A marker struct for the constrained type."]
            #[derive(Debug, Clone, Default)]
            $vis struct [<$TypeName Constraint>]$(< $($gen)+ >)? {
                $( _phantom: ::core::marker::PhantomData<($($gen)+)>,)?
            }

            // --- CONDITIONAL CONST IMPL ---
            // NOTE: Const validation does not currently support generics.
            #[cfg(feature = "const-validation")]
            $crate::__floco_const_impl! {
                $crate::Constrained<$InnerType> for [<$TypeName Constraint>] {
                    fn is_valid($val_id: &$InnerType) -> bool { $validator }
                    fn emit_error(value: $InnerType) -> Self::Error { $crate::ValidationError { value, message: $error_msg } }
                }
            }
            #[cfg(not(feature = "const-validation"))]
            impl$(< $($gen)+ >)? $crate::Constrained<$InnerType> for [<$TypeName Constraint>]$(< $($gen)+ >)?
            where
                $($($gen: 'static),+)?
            {
                fn is_valid($val_id: &$InnerType) -> bool { $validator }
                fn emit_error(value: $InnerType) -> Self::Error { $crate::ValidationError { value, message: $error_msg } }
            }

            // --- The Newtype Struct ---
            #[doc = "A validated newtype generated by the `constrained_type!` macro."]
            $(#[$outer])*
            #[derive(Debug, Clone)]
            $vis struct $TypeName$(< $($gen)+ >)?(pub $crate::Floco<$InnerType, [<$TypeName Constraint>]$(< $($gen)+ >)?>);

            // --- Serde Impls for the Newtype ---
            // We must manually implement Serialize/Deserialize for generics.
            impl$(< $($gen)+ >)? serde::Serialize for $TypeName$(< $($gen)+ >)?
            where
                $InnerType: serde::Serialize,
                $($($gen: 'static),+)?
            {
                fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
                where
                    S: serde::Serializer,
                {
                    self.0.serialize(serializer)
                }
            }

            impl<'de, $($($gen: 'static),+)?> serde::Deserialize<'de> for $TypeName$(< $($gen)+ >)?
            where
                $InnerType: serde::Deserialize<'de>,
            {
                fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
                where
                    D: serde::Deserializer<'de>,
                {
                    let value = <$InnerType>::deserialize(deserializer)?;
                    Self::try_new(value).map_err(serde::de::Error::custom)
                }
            }


            // --- Newtype Associated Functions ---
            impl$(< $($gen)+ >)? $TypeName$(< $($gen)+ >)? {
                /// Creates a new, validated instance of this type.
                pub fn try_new(value: $InnerType) -> Result<Self, $crate::ValidationError<$InnerType>> {
                    Ok(Self($crate::Floco::<_, [<$TypeName Constraint>]$(< $($gen)+ >)?>::try_new(value)?))
                }

                /// Returns a reference to the inner validated value.
                pub fn get(&self) -> &$InnerType { &(self.0).0 }

                /// Consumes the newtype and returns the inner validated value.
                pub fn into_inner(self) -> $InnerType { (self.0).0 }
            }

            // --- Newtype Deref Trait ---
            impl$(< $($gen)+ >)? ::core::ops::Deref for $TypeName$(< $($gen)+ >)? {
                type Target = $InnerType;
                fn deref(&self) -> &Self::Target { &(self.0).0 }
            }
        }
    };
}

/// Creates a new, validated type from an existing one, with optional compile-time checks.
#[macro_export]
macro_rules! constrained_type {
    // ARM 1: With default value.
    ($(#[$outer:meta])* $vis:vis type $TypeName:ident $(<$($gen:tt)+>)? ($InnerType:ty) where |$val_id:ident| $validator:expr, $error_msg:expr, default: $default_val:expr) => {
        $crate::__floco_internal_newtype_impl!{
            $(#[$outer])*,
            $vis,
            $TypeName,
            $(<$($gen)+>)?,
            $InnerType,
            |$val_id| $validator,
            $error_msg
        }

        #[cfg(feature = "const-validation")]
        const _: () = {
            // const validation does not support generics yet.
        };

        impl$(<$($gen)+>)? Default for $TypeName$(<$($gen)+>)? {
            fn default() -> Self {
                Self::try_new($default_val).expect("The provided default value is invalid.")
            }
        }
    };

    // ARM 2: No default value.
    ($(#[$outer:meta])* $vis:vis type $TypeName:ident $(<$($gen:tt)+>)? ($InnerType:ty) where |$val_id:ident| $validator:expr, $error_msg:expr) => {
        $crate::__floco_internal_newtype_impl!{
            $(#[$outer])*,
            $vis,
            $TypeName,
            $(<$($gen)+>)?,
            $InnerType,
            |$val_id| $validator,
            $error_msg
        }

        #[cfg(feature = "const-validation")]
        const _: () = {
            // const validation does not support generics yet.
        };

        impl$(<$($gen)+>)? Default for $TypeName$(<$($gen)+>)? where $InnerType: Default {
            fn default() -> Self {
                Self::try_new(<$InnerType as Default>::default()).expect("The default value of the inner type is invalid.")
            }
        }
    };
}
